[package]
name = "wager_escrow"
version = "0.1.0"
description = "Royale Wager escrow program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "wager_escrow"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []

[dependencies]
anchor-lang = "0.30.1"


